// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe0U6QokE-SQ0WCPyArXPEV9CRMcLKIOg',
    appId: '1:785506693538:web:eb019232826d65bbdd82fb',
    messagingSenderId: '785506693538',
    projectId: 'doctapp-8a31d',
    authDomain: 'doctapp-8a31d.firebaseapp.com',
    storageBucket: 'doctapp-8a31d.firebasestorage.app',
    measurementId: 'G-14VEJRTW9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGpC_G9Ce1A0xDcVNK30IE6PsWE-xxzWM',
    appId: '1:785506693538:android:103bcbc3765da6bcdd82fb',
    messagingSenderId: '785506693538',
    projectId: 'doctapp-8a31d',
    storageBucket: 'doctapp-8a31d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3aDPEuygviKUkhL4tnHMsAyWrRHoONd8',
    appId: '1:785506693538:ios:81c8cf6a1ef8d3a1dd82fb',
    messagingSenderId: '785506693538',
    projectId: 'doctapp-8a31d',
    storageBucket: 'doctapp-8a31d.firebasestorage.app',
    iosBundleId: 'com.example.healthcareapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3aDPEuygviKUkhL4tnHMsAyWrRHoONd8',
    appId: '1:785506693538:ios:81c8cf6a1ef8d3a1dd82fb',
    messagingSenderId: '785506693538',
    projectId: 'doctapp-8a31d',
    storageBucket: 'doctapp-8a31d.firebasestorage.app',
    iosBundleId: 'com.example.healthcareapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe0U6QokE-SQ0WCPyArXPEV9CRMcLKIOg',
    appId: '1:785506693538:web:78685da1c3723d19dd82fb',
    messagingSenderId: '785506693538',
    projectId: 'doctapp-8a31d',
    authDomain: 'doctapp-8a31d.firebaseapp.com',
    storageBucket: 'doctapp-8a31d.firebasestorage.app',
    measurementId: 'G-HFBLY25X3H',
  );

}